# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "2.7"
  - "bdd"
# pypy testing currently breaks because of the tempfile dir used for KALITE_HOME
#  - "pypy"

before_install:
  - pip install codecov
  - pip install tox

before_script:
  - tox -e lint

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV

after_success:
  - codecov
