# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "2.7"
# pypy testing currently breaks because of the tempfile dir used for KALITE_HOME
#  - "pypy"

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py2.7
      env: TOX_ENV=docs
      env: TOX_ENV=bdd
    - python: "3.4"
      env: TOX_ENV=py3.4
    - python: "3.5"
      env: TOX_ENV=py3.5

before_install:
  - pip install codecov
  - pip install tox

before_script:
  - tox -e lint

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV

after_success:
  - codecov
