steps:
  - label: Build Python packages
    command:
     - make docker-clean
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - label: Build Windows installer
    command: .buildkite/build_windows_installer.sh

  - wait

  - label: Build Debian Packages
    command: .buildkite/build_debian_pkgs.sh

  - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh
    if: build.tag != null

  - wait

  - label: Cleaning up
    command: make docker-clean

  - block: "Test .debs?"
  - label: Test on Trusty, Xenial, Bionic
    command:
     - mkdir -p dist
     - buildkite-agent artifact download 'dist/*.deb' dist/
     - make docker-deb-test
