steps:
  - label: Build the docker environment
    command: make dockerenvbuild

  - wait

  - label: Build the python packages
    command: mkdir -p dist && .buildkite/build_whl.sh && docker container prune -f

  - wait

  - label: Build kolibri windows installer
    command: .buildkite/build_windows_installer.sh

  - wait

  # - label: Build the Android APK file
  #   command: mkdir -p dist && .buildkite/build_apk.sh

  # - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh && docker image prune -f -a
    if: build.tag != null
