steps:
  - label: Build Python packages
    command:
     - mkdir -p dist
     - .buildkite/build_whl.sh

  - wait

  - label: Build Windows installer
    command: .buildkite/build_windows_installer.sh

  - wait

  - label: Upload Release Artifacts
    command: .buildkite/setup_and_upload_artifact.sh
    if: build.tag != null

  - wait
