name: Kolibri Build Assets for Pull Request

on: pull_request

jobs:
  whl:
    name: Build WHL file
    uses: ./.github/workflows/build_whl.yml
  pex:
    name: Build PEX file
    needs: whl
    uses: ./.github/workflows/build_pex.yml
    with:
      whl-file-name: ${{ needs.whl.outputs.whl-file-name }}
  dmg:
    name: Build DMG file
    needs: whl
    uses: learningequality/kolibri-app/.github/workflows/build_mac.yml@main
    with:
      whl-file-name: ${{ needs.whl.outputs.whl-file-name }}
      ref: main
